server:
  port: 8080

spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: UPLOAD-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/api/upload/**



